all:
  children:
    dev:
      vars:
        ansible_user: rootadm
        ansible_ssh_port: 22
      hosts:
        172.16.0.11:

    prod:
      vars:
        ansible_user: rootadm
        ansible_ssh_port: 22 
      hosts:
        172.16.0.11:
