all:
  children:
    dev:
      vars:
        ansible_user: rootadm
        ansible_ssh_port: 22
      hosts:
        192.168.0.2:

    prod:
      vars:
        ansible_user: rootadm
        ansible_ssh_port: 22 
      hosts:
        192.168.0.2:
