all:
  children:
  
    dev:
      vars:
        ansible_user: rootadm
        ansible_ssh_port: 22
        ansible_ssh_private_key_file: /root/.ssh/dev/pfs_rsa        
      hosts:
        192.168.0.1:

    prod:
      vars:
        ansible_user: rootadm
        ansible_ssh_port: 2254
        ansible_ssh_private_key_file: /root/.ssh/prod/pfs_rsa
      hosts:
        192.168.1.2:
