# Project directory before deploy
project_path: /opt/prodforsber
project_repo_url: "https://github.com/fktrctq/PFS-web.git"
project_repo_branch: prod
required_docker_version: "24.0.7"
required_compose_version: "2.24.6"

# Docker Compose
db_image: postgres:alpine3.21
vol_name: prod_pgdata_forsber
static_volume: static_data_volume
log_max_size: "10m"
log_max_file: "2"

# Name container
pg_container_name: prod-doc-pg-db
app_container_name: prod-doc-app-fs
web_container_name: prod-doc-web

# Name service
pg_service_name: prod-pg-db
app_service_name: prod-app-fs
web_service_name: prod-web

# Nginx settings
server_name: prod.ruviewer.ru
proxy_upstream: "{{ app_service_name }}:8000"
nginx_public_port: "80"
nginx_public_port_ssl: "443"

# SSL  Let's Encrypt
email_admin: "sber@sber.ru"
site_ssl: true
test_ssl_enabled: true
letsencrypt_path: /etc/letsencrypt


# Database settings
db_engine: "postgresql"
db_name: "forsber"
db_user: "dbuserfs"
db_password: "dbpswdfs"
db_host: "{{ pg_service_name }}"
db_port: "5432"
db_auth_method: "trust"
db_locale: "en-US"

# Django settings
django_secret_key: "super-secret-key"
django_debug: "false"
django_loglevel: "info"
django_allowed_hosts: "localhost,127.0.0.1,{{ server_name }},{{ web_service_name }}"
django_csrf_trusted_origins: "https://{{ server_name }}"
django_superuser_username: "sber"
django_superuser_email: "sber@sber.ru"
django_superuser_password: "sber"
django_language_code: "en-us"
django_tz: "UTC"



