    - name: Установка ufw
      apt:
        name: ufw
        state: present
        update_cache: yes

    - name: Разрешить порты через ufw
      community.general.ufw:
        rule: allow
        port: "{{ item }}"
        proto: tcp
      loop:
        - "{{ nginx_public_port }}"
        - "{{ nginx_public_port_ssl }}"
        - "{{ ansible_ssh_port }}"

    - name: Включить ufw 
      community.general.ufw:
        state: enabled

    - name: Проверить статус ufw
      command: ufw status verbose
      register: ufw_status
      changed_when: false

    - name: Показать статус ufw
      debug:
        msg: "{{ ufw_status.stdout }}"