- name: Установка переменных для проверки сертификата
  set_fact:
    threshold_ts: "{{ (ansible_date_time.iso8601 | to_datetime('%Y-%m-%dT%H:%M:%SZ')).timestamp() | int + 30*24*60*60 }}"
    cert_path: "{{ letsencrypt_path }}/live/{{ server_name }}/fullchain.pem"
    valid_ssl: false

- name: Проверяем, существует ли файл сертификата
  stat:
    path: "{{ cert_path }}"
  register: cert_file

- name: Получаем информацию о сертификате
  community.crypto.x509_certificate_info:
    path: "{{ cert_path }}"
  register: cert_info
  when: cert_file.stat.exists

- name: Получение даты окончания сертификата в timestamp
  set_fact:
    cert_expiry_ts: "{{ (cert_info.not_after | to_datetime('%Y%m%d%H%M%SZ')).timestamp() | int }}"
  when: cert_file.stat.exists

- name: Проверка даты действия сертификата
  set_fact:
    valid_ssl: true
  when:
    - cert_file.stat.exists
    - cert_expiry_ts >= threshold_ts

- name: Срок действия сертификата
  debug:
    msg: >-
      valid_ssl = {{ valid_ssl }} (сертификат истекает {{
      (cert_info.not_after | to_datetime('%Y%m%d%H%M%SZ')).strftime('%Y-%m-%d %H:%M:%S')
      }})
  when: valid_ssl
  ignore_errors: true
