
- name: Установка или обновление Docker и Docker Compose
  block:

    # ─────────────── БЛОК 1: Очистка старых репозиториев ───────────────

    - name: Удалить старые Docker репозитории
      file:
        path: /etc/apt/sources.list.d/docker.list
        state: absent
      ignore_errors: true

    - name: Удалить записи Docker из основного sources.list
      lineinfile:
        path: /etc/apt/sources.list
        regexp: '^deb .*docker.com.*'
        state: absent
      ignore_errors: true

    # ─────────────── БЛОК 2: Добавление репозитория Docker ───────────────

    - name: Установить зависимости для Docker и репозиториев
      apt:
        name:
          - apt-transport-https
          - ca-certificates
          - curl
          - gnupg
          - lsb-release
        state: present
        update_cache: yes

    - name: Создать директорию для ключей apt, если не существует
      file:
        path: /etc/apt/keyrings
        state: directory
        mode: '0755'

    - name: Добавить официальный GPG ключ Docker в /etc/apt/keyrings/docker.asc
      get_url:
        url: https://download.docker.com/linux/{{ ansible_distribution | lower }}/gpg
        dest: /etc/apt/keyrings/docker.asc
        mode: '0644'

    - name: Добавить Docker репозиторий с Signed-By
      apt_repository:
        repo: "deb [arch=amd64 signed-by=/etc/apt/keyrings/docker.asc] https://download.docker.com/linux/{{ ansible_distribution | lower }} {{ ansible_distribution_release }} stable"
        filename: docker
        state: present

    - name: Обновить кэш apt
      apt:
        update_cache: yes

    # ─────────────── БЛОК 3: Установка пакетов ───────────────

    - name: Установить или обновить Docker
      apt:
        name: docker-ce
        state: latest
      when: docker_update_required | default(false)

    - name: Установить или обновить Docker Compose
      apt:
        name: docker-compose-plugin
        state: latest
      when: compose_update_required | default(false)

    - name: Запустить и включить службу Docker
      systemd:
        name: docker
        state: started
        enabled: yes

    # ─────────────── БЛОК 4: Завершение ───────────────

    - name: Docker и Docker Compose успешно установлены
      set_fact:
        docker_installed: true
        compose_installed: true

  rescue:

    # ─────────────── БЛОК 5: Обработка ошибок ───────────────

    - name: Ошибка установки Docker/Docker Compose или зависимостей
      debug:
        msg: "Ошибка при установке Docker или Docker Compose. Проверьте подключение и права пользователя."

    - name: Задача прервана из-за ошибки установки docker и dockeer compose (v2)
      set_fact:
        docker_installed: false
        compose_installed: false
  
  tags:
    - install_docker
