---
- name: Установить зависимости для Docker и репозиториев
  apt:
    name:
      - apt-transport-https
      - ca-certificates
      - curl
      - gnupg
      - lsb-release
    state: present
    update_cache: yes

- name: Добавить официальный GPG ключ Docker
  apt_key:
    url: https://download.docker.com/linux/{{ ansible_distribution | lower }}/gpg
    state: present

- name: Добавить Docker репозиторий
  apt_repository:
    repo: "deb [arch=amd64] https://download.docker.com/linux/{{ ansible_distribution | lower }} {{ ansible_distribution_release }} stable"
    state: present
    filename: docker

- name: Обновить кэш apt
  apt:
    update_cache: yes

- name: Установить или обновить Docker
  apt:
    name: docker-ce
    state: latest
  when: docker_update_required

- name: Установить или обновить Docker Compose
  apt:
    name: docker-compose-plugin
    state: latest
  when: compose_update_required
