- name: Установка или обновление Docker и Docker Compose
  block:

<<<<<<< HEAD
    - name: Удалить старые Docker репозитории
      file:
        path: /etc/apt/sources.list.d/docker.list
        state: absent
      ignore_errors: true

    - name: Удалить старые Docker репозитории из main sources.list
      lineinfile:
        path: /etc/apt/sources.list
        regexp: '^deb .*docker.com.*'
        state: absent
      ignore_errors: true

    - name: Установить зависимости для Docker и репозиториев
      apt:
        name:
          - apt-transport-https
          - ca-certificates
          - curl
          - gnupg
          - lsb-release
        state: present
        update_cache: yes

    - name: Создать директорию для ключей apt, если не существует
      file:
        path: /etc/apt/keyrings
        state: directory
        mode: '0755'

    - name: Добавить официальный GPG ключ Docker в /etc/apt/keyrings/docker.asc
      get_url:
        url: https://download.docker.com/linux/{{ ansible_distribution | lower }}/gpg
        dest: /etc/apt/keyrings/docker.asc
        mode: '0644'

    - name: Добавить Docker репозиторий с Signed-By
      apt_repository:
        repo: "deb [arch=amd64 signed-by=/etc/apt/keyrings/docker.asc] https://download.docker.com/linux/{{ ansible_distribution | lower }} {{ ansible_distribution_release }} stable"
        filename: docker
        state: present

    - name: Обновить кэш apt
      apt:
        update_cache: yes


=======
    - name: Установить зависимости для Docker и репозиториев
      apt:
        name:
          - apt-transport-https
          - ca-certificates
          - curl
          - gnupg
          - lsb-release
        state: present
        update_cache: yes

    - name: Добавить официальный GPG ключ Docker
      apt_key:
        url: https://download.docker.com/linux/{{ ansible_distribution | lower }}/gpg
        state: present

    - name: Добавить Docker репозиторий
      apt_repository:
        repo: "deb [arch=amd64] https://download.docker.com/linux/{{ ansible_distribution | lower }} {{ ansible_distribution_release }} stable"
        state: present
        filename: docker

    - name: Обновить кэш apt
      apt:
        update_cache: yes

>>>>>>> dbe0e9253966f92c23c516e6e8a44f72772d3cbe
    - name: Установить или обновить Docker
      apt:
        name: docker-ce
        state: latest
      when: docker_update_required | default(true)

    - name: Установить или обновить Docker Compose
      apt:
        name: docker-compose-plugin
        state: latest
      when: compose_update_required | default(true)

    - name: Docker и Docker Compose успешно установлены
      set_fact:
        docker_installed: true

  rescue:
    - name: Ошибка установки Docker/Docker Compose или зависимостей
      debug:
        msg: "Ошибка при установке Docker или Docker Compose. Проверьте подключение и права пользователя."

    - name: Установить флаг docker_installed в false
      set_fact:
        docker_installed: false
